### PR TITLE
Update ibmi-minimum-levels.md

### PR DESCRIPTION
**Pull request by sammagnum**
Added explicit update for 7.5 based on internal slack:
https://ibm-systems.slack.com/archives/G01BEAY4TL3/p1665671283981159

### CODE REVIEW

**Comment by sammagnum** [comment]
@soumenon can you verify with @bsmenges  so we can specifically state no ptfs are needed for 7.5

**Comment by Itsmemukesh** [comment]
@sammagnum 
The above link for the slack description can not be accessed. The team needs to see the discussion in order to verify the changes.

**Comment by Itsmemukesh** [comment]
@sammagnum 
Please provide access.

Thanks

**Comment by Itsmemukesh** [comment]
@sammagnum Can you share the Slack discussions as I can not access them through the provided link?

**Comment by sammagnum** [comment]
Sorry for the delay, I invited you to the channel

**Comment by Itsmemukesh** [comment]
Done!
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-minimum-levels

**Pull request closed without merging**
